# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
