# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_parkingspot_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='zip',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='title',
            field=models.CharField(default=b'', max_length=25),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='zipcode',
            field=models.CharField(default=b'', max_length=5),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='city',
            field=models.CharField(default=b'', max_length=15),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='owner',
            field=models.CharField(default=b'', max_length=25),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='state',
            field=models.CharField(default=b'', max_length=2),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='street',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
