# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_parkingspot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='user',
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
