# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170309_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='posttime',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='city',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='street',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='title',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='zipcode',
            field=models.CharField(default='', max_length=5),
        ),
    ]
