# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170312_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='posttime',
            field=models.DateTimeField(default='YYYY-MM-DD'),
        ),
    ]
